apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: sunnytyagi13/user-api:64db6f8
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            # ---------------------------
            # Application
            # ---------------------------
            - name: PORT
              value: "3000"

            # ---------------------------
            # MongoDB
            # ---------------------------
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/callbooking"

            # ---------------------------
            # Admin email (receiver)
            # ---------------------------
            - name: ADMIN_EMAIL
              value: "admin@deekshithsn.co.in"

            # ---------------------------
            # SMTP (OPTIONAL for DEV)
            # ---------------------------
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_HOST
                  optional: true

            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_PORT
                  optional: true

            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_USER
                  optional: true

            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_PASS
                  optional: true

          # ---------------------------
          # Health checks
          # ---------------------------
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20

          # ---------------------------
          # Resources
          # ---------------------------
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
