apiVersion: v1
kind: Service
metadata:
  name: user-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: user-api
  ports:
    - port: 80
      targetPort: 3000
