apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
  labels:
    app: admin-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      containers:
        - name: admin-api
          image: sunnytyagi13/admin-api:ac6c309
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/callbooking"
