apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
  labels:
    app: admin-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-ui
  template:
    metadata:
      labels:
        app: admin-ui
    spec:
      containers:
        - name: admin-ui
          image: sunnytyagi13/admin-ui:18b4e63
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
