name: Admin API CI

on:
  push:
    paths:
      - "admin-api/**"
  pull_request:
    paths:
      - "admin-api/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: admin-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: admin-api/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: user-ui
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Run tests (optional)
        run: npm test --if-present

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker build \
            -t sunnytyagi13/admin-api:latest \
            -t sunnytyagi13/admin-api:$SHORT_SHA \
            .

      - name: Push Docker Image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker push sunnytyagi13/admin-api:latest
          docker push sunnytyagi13/admin-api:$SHORT_SHA
