name: Admin API CI

on:
  push:
    paths:
      - "admin-api/**"
  pull_request:
    paths:
      - "admin-api/**"

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: admin-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        run: mvn clean package -DskipTests

      - name: Docker Build
        run: docker build -t sunny008/admin-api:${{ github.sha }} .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        run: docker push sunny008/admin-api:${{ github.sha }}
