name: Admin UI CI

on:
  push:
    paths:
      - "admin-ui/**"

jobs:
  build-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: admin-ui

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: admin-ui/package-lock.json

      # 3️⃣ Install & build UI
      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: admin-ui
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Build UI
        run: npm run build

      # 4️⃣ Docker login (using token)
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Build Docker image with multiple tags
      - name: Build Docker Image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker build \
            -t sunnytyagi13/admin-ui:latest \
            -t sunnytyagi13/admin-ui:$SHORT_SHA \
            .

      # 6️⃣ Push Docker images
      - name: Push Docker Image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker push sunnytyagi13/admin-ui:latest
          docker push sunnytyagi13/admin-ui:$SHORT_SHA
